### ISSUE TITLE
Does not work on CD32

### ISSUE THREAD

**Issue by kikendo** [keirf/Amiga-Stuff#1]
Burned this to a bootable CD and it doesn't work on the CD32.
Also tested loading it from an IDE drive attached to my CD32 and it didn't work.

Loads to the menu screen, but shows no text and it's locked up there.

Find ISO attached. Behaves the same way in WinUAE with CD32 config.
[systestCD32.zip](https://github.com/keirf/Amiga-Stuff/files/1334521/systestCD32.zip)

Sept 17 2017 20:00:25 build is the one that doesn't work. Seems like some people have another version that does? Still trying to determine this.

**Comment by keirf** [comment]
Okay we confirmed the workaround still works. I will close this as won't-be-properly-fixed.
