### ISSUE TITLE
Clock not detected on A500+ with TF534 Accelerator

### ISSUE THREAD

**Issue by dandoore** [keirf/Amiga-Stuff#11]
Amiga A500+, Gotek, KS ROM 3.1.4, Trapdoor 1Mb, TF534 Accelerator (68030/50Mhz, 4Mb RAM in Z3 space, FPU and IDE)

If I boot the test kit with a vanilla 68000 CPU it sees the Oki clock in the test and I can set it and reset it fine and groovy.

When I boot with the TF accelerator the test kit says ** No Clock Detected **, but in Workbench (3.1.4) I can see and set the time just fine.

**Comment by keirf** [comment]
Have you asked the TF author if the accelerator does anything explicit that could/does affect rtc access? Otherwise I will take a look at the ATK code. But I don't have a TF for testing.

**Comment by dandoore** [comment]
I'm about to do the same on the Exxos forum shortly :)

**Comment by dandoore** [comment]
Although it works fine with the TF in from Workbench :-S

**Comment by keirf** [comment]
Doesn't look like there's progress on this one?

**Comment by dandoore** [comment]
> Doesn't look like there's progress on this one?

Nothing has been said on other forums, although I did spot something in the changelog for WB 3.1.4 that might have relevance, or at least explain why the clock is working under WB:

```
Similar speed brakes went into the battclock.resource because fast 
CPUs were just too fast for the slow real time clock. This fixed  issues especially related to the Vampire. Thanks to the Vampire team for the report.
```

**Comment by keirf** [comment]
It's possible. I suppose you could test an older Kickstart and Workbench? I think it's unlikely to be related as Vampire is a *lot* faster than any real Motorola CPU, especially a 68030.

**Comment by dandoore** [comment]
I tested with KS2.04 and booting into Testkit did the same, booting into KS2 saw the clock fine.

**Comment by dandoore** [comment]
Also Gadget on the exxos forums found the same: https://www.exxoshost.co.uk/forum/viewtopic.php?f=68&t=1845&start=40#p24896

**Comment by keirf** [comment]
I need to make a debug build which will tell us why clock detection fails.

**Comment by keirf** [comment]
Hi, It's been a while, but here is a debug build which will print a cryptic line about where the clock detection failed. Please run it and report what the line below "No Clock Detected" says.

[ATK-11-1.zip](https://github.com/keirf/Amiga-Stuff/files/3662565/ATK-11-1.zip)

**Comment by dandoore** [comment]
> Hi, It's been a while, but here is a debug build which will print a cryptic line about where the clock detection failed. Please run it and report what the line below "No Clock Detected" says.

Our survey said:

0A,f4,84:1A,ff,87:

Dan

**Comment by keirf** [comment]
Ok it fails at the very first step of detection. Let's try putting in a massive delay after every write. Here's another build to try:

[ATK-11-2.zip](https://github.com/keirf/Amiga-Stuff/files/3664099/ATK-11-2.zip)

**Comment by dandoore** [comment]
\o/

That works, returns code 0: and detects MSM6242 at 00dc0000 with correct time, I could also reset and set the time fine too,

**Comment by keirf** [comment]
Excellent. Could you please try this more considered fix, which is a proper candidate for next release. Same testing as before if you don't mind:

[ATK-11-3.zip](https://github.com/keirf/Amiga-Stuff/files/3664776/ATK-11-3.zip)

**Comment by dandoore** [comment]
No problem - and yes, it works fine :-)

**Comment by SukkoPera** [comment]
I was going to report the same bug affecting my A500+TF530 setup but tested the latest version first and I can confirm that it now works fine :).
