### ISSUE TITLE
Support of Amiga 1000

### ISSUE THREAD

**Issue by leonpierre** [keirf/Amiga-Stuff#12]
Currently the Testkit doesn't work with Amiga 1000! It would be great if you extend it to also cover this computer!

**Comment by keirf** [comment]
It's supposed to work and I'm pretty sure it has worked in the past. What happens?

**Comment by leonpierre** [comment]
I only see the Kickstart symbol after 2 seconds and nothing more! With DiagROM I can test the Amiga 1000!

**Comment by keirf** [comment]
So you boot the kickstart disk and then load the TestKit disk and it crashes?

Is this 256k ram? Which kickstart?

**Comment by leonpierre** [comment]
No, boot of kickstart is not possible. This is why I need a testkit to see what's wrong! Can I include your testkit to a kickstart disk?

**Comment by keirf** [comment]
Oh I see. You can only boot a kickstart disk (or I guess "rom disk" since I assume you have written diagrom to a boot disk). TestKit is a normal disk so you have to load kickstart first. If you can't, system may well be broken enough that you need diagrom anyway.
