### ISSUE TITLE
RTC test hangs on my A4000D

### ISSUE THREAD

**Issue by aliastra** [keirf/Amiga-Stuff#18]
This is gonna be a short novel but please bear with me.

A while back I got an A4000D Rev B with some very mild corrosion from the leaking battery. It appeared to be in very nice shape overall, but looks can be deceiving :)
Machine was constantly in reset state - fixed, mouse input was erratic - fixed, audio channels had difference in amplitude - fixed, Zorro cards were not being recognized - fixed etc etc...

Anyway, during the fixing period I was using ATK 1.4, among other things, to check on the issues. 3 chips below the RTC (U177, U975 and U976) were replaced (RTC chip was left intact) together with some other stuff and everything appeared to be working fine, RTC included.

I had no time to play with the Amiga no more but resumed work a few days ago. Meanwhile ATK 1.5 was released and I started using it without much though, just to retest the motherboard quickly before i start putting everything back in the case. However, RTC test would constantly semi-hang the machine after a random period of time (from few seconds up to few minutes). So, completely baffled, as I was pretty sure everything was working fine a while back I went to replace the resistor pack and RTC chip just because I had spare anyway.
Ok, fine, I'm good to go now, for sure. Well... no, ATK was still semi-hanging on RTC test. WTF WTF Panic! So, as RTC seamed to be working fine from DOS I decided to give ATK 1.4 a go, and it works fine.

I'm not sure what has been changed from 1.4 to 1.5 but I've now left 1.4 running on 2 separate occasions for 24 hours on the RTC test screen and it survived, while 1.5 constantly semi-hangs after a short period of time.
What I mean by semi-hanging could best be described as time no longer updates, keyboard input is no longer registered, input from the mouse buttons is no longer registered but mouse cursor can be moved around and items do highlight when you mouse over them, just can't actually navigate anywhere any more.

**Comment by keirf** [comment]
Thanks for the report. I think this is an incredibly stupid C arithmetic bug in Test Kit. Let me spin you a possible fix to test.

**Comment by keirf** [comment]
Here you go, please soak this for a few hours and report back:

[atk_18_1.zip](https://github.com/keirf/Amiga-Stuff/files/4297049/atk_18_1.zip)

**Comment by aliastra** [comment]
I've put the old RTC chip back and ran this build for more than 12 hours straight. It's still alive. However, my time has gone 6 minutes late during this period and I've also found out one of the fast ram simms has gone bad. I'd swear this motherboard is haunted, Whenever you look at it something strange fails.
