### ISSUE TITLE
Joystick in port #2 detected as mouse on real & emulated A1200 (running Kick 3.1+accel card)

### ISSUE THREAD

**Issue by Drag0nFly** [keirf/Amiga-Stuff#2]
_[ Firstly, thanks for this *very useful* test suite - I'm running it on all my Amigas to diagnose any faults. Only thing really missing is maybe more extensive gfx diagnostics (blitter/copper/Agnus etc.)! And a way to quit the utility when running via Workbench is also useful ]_

However, I noticed a minor issue with the Mouse / Joystick / Gamepad check:

Both ports are detected as mice on my A1200 (w/ rev 1d4 mainboard) using a Tac-2 stick which was properly detected as such on my A500. The same also occurs when running SysTest via FS-UAE (emulating an A1200) and using a USB-joystick on OSX through the emulation layer.

This is using the (AFAIK) most recent SysTest release from Feb 18th, 2017.

**Comment by keirf** [comment]
There is no auto-detection of connected device. Until September I was defaulting both ports to mouse. 
I then did an update in September which changed the port-2 default to joystick.

So your observation sounds like you may simply be running two different versions of SysTest? There is a build date displayed at the bottom of the main menu screen which you can check.

Regarding your other points, SysTest tramples memory and I'm unlikely to bother to fix that to allow quit to Workbench. Also the program does use the copper and blitter in some cases so they do get a bit of a work out. :)

**Comment by Drag0nFly** [comment]
Thanks for that clarification, Keir. I thought I was using the most recent versions, as I downloaded the suite and simply used the .adf on the 500 and the standalone executable on the A1200 - but your explanation sounds plausible and I'll double-check.

As regards to the gfx comment, maybe I'm missing something but I only saw the RGB-screen when running the video test? Or maybe something else is happening behind the scenes. :)

And yes, quitting to WB after randomly writing to the memory regions also does not sound like a good idea. ;)

**Comment by Drag0nFly** [comment]
I was going to say all was good after I re-downloaded the SysTest executable and verified that it was indeed the Sept. 2017 version and the joystick came up in port #2 and was tested successfully. Then a few minutes later it crashed the A1200. :-/ A minute or so later, the bottom display, below the stacktrace, got garbled, and shortly adter this the display also went blank. /me shivers as a lot of money was thrown into this A1200...

Curiously, I ran five complete memcheck passes previously (2Mb chip region, 1Mb "mid" region & 126Mb accelerator mem) *without* a crash. But since the aim was to detect issues with the Amigas it appears I have managed this with flying colors. :p

**Comment by keirf** [comment]
You can email the stacktrace to me, my email is on my Github profile page. It is almost certainly a hardware problem, especially with an Accelerator attached, and especially if the crash handler (which after printing diagnostics simply loops forever with interrupts disabled) crashes.

I will close this issue now.
