### ISSUE TITLE
AmigaTestKit: Amiga 1000 incorrectly detected as PAL

### ISSUE THREAD

**Issue by DLehenbauer** [keirf/Amiga-Stuff#23]
AmigaTestKit v1.10 incorrectly detects my Amiga 1000 as a PAL machine.

The machine is a unmodified NTSC model / Rev 6 motherboard:
* 28.3636 mhz crystal
* 8361R3 Agnus

The Chipset IDs shown on the CIA / Chipset menu are '0000' for Agnus and 'ffff' for Denise.

**Comment by DLehenbauer** [comment]
It's not just Amiga Test Kit:
- 'WhichAmiga' reports 'OCS PAL Agnus 8367'
- 'SysInfo' reports 'STD AGNUS - 512' and 'Mode: PAL'

Possibly it's a quirk of the "thin" Agnus used in A1000s.

If so, it's not a quirk that WinUAE emulates.  Emulating an A1000 w/NTSC OSC and chipset extra = A1000, ATK sees chip id =10 (NTSC).

**Comment by keirf** [comment]
Okay here is an updated version of ATK for you to try. The source for this is on branch `issue-23` of the repository.

[atk_23_1.zip](https://github.com/keirf/Amiga-Stuff/files/4890153/atk_23_1.zip)

**Comment by DLehenbauer** [comment]
That totally works!  A1000 is correctly detected as OCS/NTSC (...and now passes CIA timer tests.)

I think all of the Agnus chips with id=00 are 512k variants, which IIRC are incapable of switching between NTSC/PAL (i.e., no risk choosing the wrong 'cpu_hz' if someone boots an NTSC machine in PAL mode, or vice-versa).

One paranoid thought: is there any chance that choosing between PAL/NTSC by comparing VBLs vs. CIA ticks might mask failures in the timer tests?  (I don't know.  I just noticed that the CIA timer tests seem to be doing similar comparisons.)

Anyway, I think it's a fascinating problem and am happy to volunteer my A1000 for future ATK testing.  Ping me any time!

**Comment by keirf** [comment]
It won't mask grotesque errors, only errors in the region of a couple of percent. And of course the new test depends on functioning CIA timer. Hence I use the existing PAL/NTSC detection unless the Agnus ID is 00. I think that's as rigorous as we can possibly be.

**Comment by DLehenbauer** [comment]
Reading the source for 'WhichAmiga' ([here](https://www.sintonen.fi/sw/WhichAmiga.lha)) it distinguishes a "thin" Agnus (8361/8367) vs. a "fat" Agnus (8370/8371) by checking for a known bug in the chip:
```
.subr	move.l	(ExecBase00,pc),a6	;Test for 8361/8367 Agnus:
	call	Disable
	moveq	#32,d6			;Multicheck: 32 times
	move.l	_GfxBase,a6
	lea	$DFF000,a5		;Loads of preloads:
	lea	(bltsize,a5),a4
	lea	(dmaconr,a5),a3
	moveq	#$41,d4			;Shortest possible blit
	call	OwnBlitter
	move.w	(a3),d5			;Save dmacon
	move.w	#DMAF_BLITHOG,(dmacon,a5) ;<- No nasty blitter, please!
.blitloop	call	WaitBlit		;Do it right, but only here! :-O
	move.w	#$0E00,(bltcon0,a5)	;Dummy blit, no dest
	bra.b	.blitcnop
	CNOP	0,4			;Align to longword
.blitcnop	move.w	d4,(a4)			;/ Fetched in   \
	move.w	(a3),d0			;\ one longword /
	btst	#DMAB_BLTDONE,d0	;<- _Very_ old agnus
	beq.b	.old_agnus		;   get this wrong!!!
	subq.l	#1,d6
	bne.b	.blitloop
	addq.b	#2,d7
.old_agnus	or.w	#INTF_SETCLR,d5		;Restore dmacon
	move.w	d5,(dmacon,a5)
	call	WaitBlit		;Wait blit to finish, if any
	call	DisownBlitter
	move.l	(ExecBase00,pc),a6
	call	Enable
	rts
```
Might not be worth the effort, but ATK could potentially use the above technique to narrow the VBL timing test in `detect_ntsc_8361()` to only machines with a "thin" Agnus (i.e., just old A1000s like mine.)

Another fun quirk I learned about in the 'WhichAmiga' source is that chip id reported by early OCS revisions of Denise can change:
```
	lea	($7C,a5),a0		;Preload denise/lisa ID hw addr
	move.w	#$FF,d3			;Preload 'and' value

	moveq	#1-1,d0			;!! These two just disable the
	bsr	HWWait			;!! annoying flick effect...
	move.w	(dmaconr,a5),d1		;Save old dmacon
	or.w	#DMAF_SETCLR,d1
	move.w	#$3FF,(dmacon,a5)	;Disable all dma
	move.w	(a0),d0			;!! OCS denise gives value $FFFF 
					;! when all dma is off (hmm?)
	move.w	d1,(dmacon,a5)		;Enable dma again
	not.w	d0			;!! Well, my old trusty A500 does!!
	beq.b	.OCS			;!! (CAN'T BE SURE ABOUT THIS)

	move.w	(a0),d0		 	;Get ID
	and.w	d3,d0
	moveq	#128-1,d2		;Check 128 times (try to notice old denise random)
.loop	move.w	(a0),d1			;Get ID again
	and.w	d3,d1
	cmp.b	d0,d1			;Same value?
	bne.b	.OCS			;Not the same value, then OCS Denise
	subq.l	#1,d2
	bpl.b	.loop
```

...and sure enough: ATK sometimes reports the chip ID of Denise as 'ffff' and sometimes as '0000'.  :-)

(Just sharing in case it's helpful / interesting.  Feel free to ignore.)

**Comment by keirf** [comment]
Thanks for these!

Regarding the blitter bug, it is hard to reproduce (hence WhichAmiga iterating 32 times). I will stick with what we have now in TestKit: startup already relies on vblank irqs basically working, and the worst case is that we misidentify an NTSC as PAL or vice versa. It is small beans really.

The Denise ID weirdness is actually because those chips do not have an ID, so you get randomness on the data bus.
