### ISSUE TITLE
EPROM Version

### ISSUE THREAD

**Issue by SukkoPera** [keirf/Amiga-Stuff#3]
Would it be possible to make a ROM image of this? Something that can be burned on an EPROM and put on a real, driveless Amiga?

**Comment by keirf** [comment]
Yes this could be done, it would be some effort, but there is init code in John Hertell's open source diagrom. But possibly it is better just to use diagrom in this case?

**Comment by SukkoPera** [comment]
I find that diagrom and SysTest are both useful in different contexts. The former is more low-level, while the latter is useful to test "almost-working" Amigas. Having SysTest on a Kickstart Switcher could be handy if the machine suddenly doesn't boot properly and you need to run a RAM or drive test. These things aren't just as easy to do in diagrom.

**Comment by terriblefire** [comment]
I believe there is an effort to put the ram and drive tests from systest in DiagROM. This would make more sense than putting systest in rom.. I think systest uses some OS/Kickstart calls that would need ripped out if the OS was missing.

**Comment by keirf** [comment]
Systest (now Amiga Test Kit) does use Kickstart a little at start of day, mainly to detect RAM. Nothing particularly insurmountable, but still time and effort. Overall I agree putting more features into diagrom makes sense rather than try to supplant diagrom in its domain (rom based diagnostics). There's no good or need to compete with another fine open source Amiga tool.

**Comment by SukkoPera** [comment]
To me they do not look like competing tools. I'm repeating myself here, but SysTest/ATK is much more user-friendly and useful in many more situations wrt diagrom. The latter is mostly useful when a machine won't boot at all. But if I have to test a floppy drive, a RAM expansion, an RTC chip or a joystick/mouse, I would never think of bringing up diagrom.

Talking about floppy drives, SysTest is useful to get drives aligned properly, but then if a drive is not aligned, it won't boot the SysTest floppy. You can use a working drive and switch on the fly, but it's something I don't like to do regularly.

Also, many times you are troubleshooting barebone mainboards, where you don't have a floppy drive connected, and you need to onnect one just to boot SysTest, then disconnect it again, do some fixes, reconnect the drive, etc... Aaaargh!

I see it's not going to be trivial to make a ROM version, but IMHO it would make this useful tool even more useful. Just my €0.2 though :).

**Comment by keirf** [comment]
Yes you do need to connect a drive but I can't see that is much aggro? It's two extra connections, assuming using the internal header, while you are connecting monitor, and keyboard and/or mouse.

To do head alignment, boot from DF1 with the bad drive in DF0. You may have to switch out KS 1.2/1.3 for a KS 2 or later ROM. Yes you need an external drive, but you'd really want one to test external drive port anyway.

**Comment by SukkoPera** [comment]
Yup, I know there are workarounds, but they're all a bit annoying, or maybe you just don't have a working external drive.

Anyway, no problem, I guess it's more annoying to turn this into a ROM and I'm fine with that :). Unfortunately I can't really help with this, so just forget it :).

**Comment by keirf** [comment]
Harmless to leave it open. There's nothing else in the ticket list. ;) It's not actually that hard to do a quick ROM version -- I think RAM detection is the main thing that would suffer, but could at least detect chip and slow ram.

**Comment by keirf** [comment]
On reflection this will never get done!
