### ISSUE TITLE
Different detection for 'Kickstart' and 'Direct' memory scan

### ISSUE THREAD

**Issue by tlepley** [keirf/Amiga-Stuff#34]
Hello,

I've run the latest release version (on an A1200 with a 8mb trapdoor extension) and I get a strange memory detection:
- Kickstart memory scan : chip 2Mb, **fast 8Mb**
- Direct memory scan: chip 2Mb, **fast 4Mb**

It's not really clear to me what is the difference between both memory scan types and what can drive to this different detection.

When I run the test, I get errors starting at address 0x60000, what corresponds to the second 4Mb of fast ram that is not detected by the 'direct' memory scan.

Any hint on what is going on would be very helpful :)

**Comment by keirf** [comment]
Kickstart scan is as reported in kickstart memory pool. How much fast do you see reported in Workbench? Perhaps kickstart is getting confused by your fast ram expansion? TestKit's own scan (direct scan) checks carefully for mirrored regions and rejects them as not true ram.

**Comment by tlepley** [comment]
- The workbench also detects 8Mb of 'other memory', like the kickstart scan, what is correct because I've put 8Mb of memory on the extension and I've properly configured the jumpers on it.
- The test program of my expansion card also detects 8Mb

But at the end, even the test program of my extension card fails when reaching the second 4Mb of fast ram.

So I assume there is something wrong with the A1200 or the extension that was detected by the 'direct scan'. At the end, even if there are 8Mb of physical memory, only 4mb are currently usable.

The question is now: what is the exact reason why the direct scan has discarded 4Mb of fast memory (which region was considered as mirrored and why).

**Comment by keirf** [comment]
Either the second 4MB is not there at all, or it's probably a mirror copy of the first 4MB.

Maybe the RAM you used is not really 8MB? In any case it's not an ATK issue.

**Comment by tlepley** [comment]
Thanks for your feebacks. I's indeed not an ATK problem. I think it's a problem of the board itself (apparently some other people have a similar problem).

For ATK, I guess that a nice feature could be to detect any inconsistency between the kickstart and direct scan, and to display more information about this difference. I think it could help debugging the issue people can have.
