### ISSUE TITLE
Add support for HD disk drives to testkit

### ISSUE THREAD

**Issue by tkurbad** [keirf/Amiga-Stuff#36]
Hi,

would it be possible to add the means for supporting HD disk drives (1760 kB) in testkit?

They assert a oscillating READY pattern instead of the constant 0xFF sent by DD drives, resulting in a drive id of 0x55555555 instead of 0xFFFFFFFF. Also, the drive's motor spins at only half the speed resulting in READY taking twice the time of being pulled low upon motor startup and INDEX pulses only about every 400 ms for HD disks.

While both the READY pattern is correctly read (while being interpreted as drive id ???) and the INDEX signal timing is showing as being correct, I get warnings about late or missing READY. Also, the read and write tests fail. I think they assume the flux of a 880kB disk coming from the drive regardless of id pattern and timing.

I know that real HD drives in Amigas are rather rare. But I've come up with a little board that mounts inside a Sony floppy to achieve just the right id sequence and ready timing as well as having the motor run at half speed, and I want to get it as accurate and similar to the unobtainable FZ357A as possible. Testkit would be a wonderful tool to test such converted drives, especially when combined with other floppy drives, Goteks, etc. and connected as DF1: in bigbox Amigas. I'd be very grateful if my suggestion could be put on the roadmap.

Thanks in advance,
Torsten

**Comment by keirf** [comment]
Late or missing Ready may be unrelated to HD vs DD issues. The message relates to Ready signal behaviour after the motor line is asserted: we would generally expect Ready to assert within 500ms. Actually drives often don't manage this and of course modified pc drive may not have Ready signal at all. Hence the message.

So it sounds like the only issue is reading and writing a HD disk? The ID stuff with alternating ID sequence is okay as is?

**Comment by keirf** [comment]
By the way I think an HD Amiga drive only produces the HD ID when an HD disk is inserted? This is checked for on DSKCHG deassert to test whether the new disk is DD or HD.

Another question: have you been able to ascertain whether the correct ID is 55555555 or AAAAAAAA, as reported by Amiga Test Kit. I'm pretty sure only one will be accepted as valid by AmigaOS but I don't know which and there is confusion in docs because the ID signalling is active low. This might help me clean up this aspect of Flashfloppy's Amiga HD handling.

**Comment by keirf** [comment]
Just did a bit of googling. It looks like it would make sense for ATK to match DriveID tool in interpreting ID sequence. This means read Ready line signalling as low=0 and high=1 (ie non inverted). Then DD = 00000000, HD = AAAAAAAA, I believe. No drive = FFFFFFFF.

**Comment by tkurbad** [comment]
Hi @keirf , thanks for the quick reply. Yes, READY is active low and what you suggest in your last reply sounds absolutely right.
My modified prototype works as expected with Amiga OS. The id sequence is asserted as follows for an idle drive:
- no disk or HD disk: 0xAAAAAAAA
- DD disk 0x00000000
For a drive with motor running, it's always 0x00000000 but only after motor is at target RPM, i.e. after two INDEX pulses at the earliest.

**Comment by tkurbad** [comment]
Actually, I'm a bit unsure about how idle DD drives behave when READY is handled correctly, especially if the drive is anything else than DF0:

**Comment by tkurbad** [comment]
Also yes: The SEL sequence to id the drive is reissued after a disk change and the disk used is reevaluated. This way you can use DD disks in a HD drive.

**Comment by keirf** [comment]
Thanks for the confirmation on IDs. 

Regarding READY with motor on, it was previously my understanding that drives should "get there" in 500ms. This is baked into many trackloaders which ignore READY or can work around it when it's missing. It's indirectly referenced in the HRM via the Chinon timing diagram (but only as a min time from MOTOR to WGATE; no time is indicated MOTOR to READY now I look again). And quite a few drive data sheets do say max time MOTOR to READY is 500ms.

But I will agree it's not a guarantee. The HRM doesn't state it or guarantee it. And clearly a lot of drives don't manage it!

So, perhaps I should not comment on any MOTOR-to-READY latency less than say 750ms? Have you ever seen the "No READY signal" message? That would be hitting the 1000ms timeout. You mention missing READY message in your OP; that's not actually an ATK message so I want to check exactly what sort of MOTOR-to-READY latencies you are seeing.

**Comment by keirf** [comment]
Finally, regarding ID when drive is empty. I don't know if it matters but I've assumed the ID then is usually 00000000 (same as when a DD disk is inserted). Backed up by this: http://www.amibay.com/showthread.php?73920-Chinon-HD-drive-won-t-read-HD-floppies/page3 (second post down on that page).

But... Quite probably it doesn't matter either way when the drive is empty!

**Comment by tkurbad** [comment]
It matters the most for an empty drive. If READY is constantly 0x00000000 during boot up for empty DF0: you will get a requester "Please insert disk DF0: in any drive" and all sorts of weirdness in Workbench besides a definitely dysfunctional DF0:

**Comment by tkurbad** [comment]
However, for DF1: upwards this seems to be handled differently and that's where I'm stuck somewhat.
On the matter of late READY: All trackloaders I know of boot from DD disks. Here, the motor should be at speed after the 3rd INDEX pulse (time stamps 0, 200 ms + spinup time, 400 ms + spinup time) at most, hence the 500 ms assumption. This will work for a HD drive as well because of the normal spinning rate of the motor.

**Comment by keirf** [comment]
Well, if I run FlashFloppy with `interface=amiga` then it permanently asserts READY (zero volts) unless an HD image is mounted. If I run FlashFloppy as DF0, with no disk inserted, and boot from DF1 into Workbench 3.1, I see no DF0 weirdness at all. No requesters. I can insert/remove disks as normal. Which is hardly surprising: DF0 here is only acting like DF1-DF3 are expected to. The fact DF0 will work without usually asserting any ID is just a hack to avoid ID circuitry because all Amigas are assumed to have DF0.

**Comment by tkurbad** [comment]
Hmm, asserting one or the other value constantly doesn't seem right either. At least to my understanding, the primary use of READY has been to determine when the drive's motor is at its desired RPM rate. The id sequence is just a kind of "misuse" because no other signals are freely available on the floppy interface. In essence, there must be periods when READY is high for a DD drive as well. If this wasn't so, IDing the other drives would always lead to them being recognized as DD because it's an open collector signal shared between all drives, thus an individual drive can only pull the signal low and not high, but does so for the whole bus...

**Comment by tkurbad** [comment]
I guess I'll have to take out my logic analyzer again to see what a real Amiga DD drive does to READY upon bootup...

**Comment by keirf** [comment]
Well yes, when I say flashfloppy is configured to permanently assert Ready, I actually mean only while it's drive select is asserted. But apart from that caveat it is permanently asserted. Actually Goteks don't generally use motor signal and in this case it works okay. When motor is asserted there is zero delay to Ready asserted because gotek is solid state and no spin up time. When motor is deasserted flashfloppy is correctly sending the 3.5 DD drive id.

**Comment by tkurbad** [comment]
Well, I guess the story goes as follows:
For DD drive:
- if idle, i.e. motor off, assert READY low as long as SEL for the drive is low
- if motor on, assert READY low as soon as motor is at RPM and keep it asserted until motor off or drive no longer SELected

For empty HD drive or when HD disk inserted:
- In idle mode, toggle READY with each rising edge of the drive's SEL signal 
- when motor is turned on, do the same READY signalling as a DD drive 
- if DD disk is inserted, behave like a DD drive

Does that sound about correct to you?

**Comment by keirf** [comment]
Yes except I believe it is normal to behave as a DD drive when an HD drive is empty.

**Comment by tkurbad** [comment]
That's difficult to achieve in hardware, because the DD detection switch is active low as most floppy signals. I've got one of those Mikronik HD drives that asserts the HD sequence if empty as well.

**Comment by tkurbad** [comment]
I also think, for an empty drive, what exactly is signalled doesn't matter much as long as the drive says "I'm here" in some valid way, but I'm not entirely sure about that. As mentioned, real trouble with READY starts at the point when more than one drive is connected...

**Comment by tkurbad** [comment]
Or better to  say: READY has to behave just right for each individual drive then.

**Comment by keirf** [comment]
Yes agreed in practice it probably doesn't matter whether you signal HD or DD when drive is empty. I think it's more usual to do the latter but either probably works.

READY shouldn't be a problem in multi-drive environment as long as each drive only drives READY when that drive is selected?

**Comment by tkurbad** [comment]
Yes, in general that's certainly true. But HD drives emit their sequence which alternates READY on _rising_ SEL, which is quite unusual, but is the way it works. So, my guess would be that trackdisk.device copes with that in multi-drive setups internally.

**Comment by tkurbad** [comment]
It's also noteworthy that C= only ever shipped the A4000 with dual HD drives. All other big boxes only could have a HD drive as DF0: and subsequent drives as DD. That might be due to the fact that the A4000 handles the motor signal differently.

**Comment by keirf** [comment]
Internally when wanting to obtain drive id, the trackdisk.device will simply pulse that drive's SEL line the required number of times. When not reading the id, the Amiga will not care about Ready state of the drive when motor is off.

The reason other big box Amigas wouldn't support an HD drive apart from DF0 is that the DD drive-id logic is on the mainboard and would overrule the alternating ID pattern generated by the drive. I believe on A4000 this mainboard behaviour could be disabled by jumper.

**Comment by tkurbad** [comment]
Yes, you are right. There's a jumper that has to be set when DF1 is DD and open for no or HD DF1.

**Comment by keirf** [comment]
Anyway, back to the original intent of the ticket: I will implement HD support today.

**Comment by rjnorthrow** [comment]
Hi Both,

I have an Amiga 4000D with a standard Chinon FB-357A HD floppy drive and happen to have a second drive (Chinon FZ-357A) which I've now put in the Amiga after reading this thread. I have J351 set to closed (second HD floppy) and J352 set to 1-2 (internal DF0 and DF1). If you would like me to do any testing, I'd be happy to help. Running ATK with both drives reveals that DF0 is initially detected as 55555555 (???) and DF1 as FFFFFFFF (present) but if I move around the menus, DF0 sometimes changes to FFFFFF(Gotek?), e.g. after a read test. In Workbench, everything seems to be fine except for when accessing DF0, the DF1 busy light comes on at the same time(?!).

**Comment by tkurbad** [comment]
@keirf thank you so much, it's now much more clear to me: The drive id sequence always ends with READY being deasserted, regardless of the drive being DD or HD. That leaves READY in the right state for the next drive in the chain. Afterwards, it's unimportant whether the drive continues to toggle READY or not until the motor is turned on and the drive selected, which is the moment when READY matters again.
This will help me greatly to remove the remaining flaws from my implementation.
Btw., if I'm not mistakenthe FZ357A achieves the toggling of READY by a flip-flop that is clocked by SEL, set in toggle mode by the DD switch and reset by the motor signal. Thus, the drive would toggle READY in idle state as well. But I don't have such a drive and can't check.

**Comment by tkurbad** [comment]
@rjnorthrow That would be most appreciated if you could do some testing. Then I could rely on testkit for my project which would make it much less difficult to get the different combinations right.

**Comment by tkurbad** [comment]
@rjnorthrow As for the simultaneous lighting of the LED, do you have a straight floppy cable or one with s small twist at the end?

**Comment by rjnorthrow** [comment]
I have a twist at one end. DF1 is attached at the end of the cable.

**Comment by tkurbad** [comment]
Put DF0 after the twist and your LEDs should be fine.

**Comment by rjnorthrow** [comment]
I will try that, thanks!

**Comment by keirf** [comment]
Okay here is a HD-enabled ATK build for you to try. The head calibration test has not been updated, but the read and write tests have: Just be sure to insert an HD disk before starting the read or write test.

[atk_36_1.zip](https://github.com/keirf/Amiga-Stuff/files/5323146/atk_36_1.zip)

**Comment by rjnorthrow** [comment]
Test results with DF0 as FB-357A/DS0 on twisted cable and FZ-357A/DS1 on cable middle (LEDs still light simultaneously for DF0 but not DF1):

IDS:
. DF0: AAAAAAAA (DS-HD 80)
. DF1: 00000000 (DS-DD 80) - not sure why it thinks it's DD, I will double-check the mobo jumpers

DF0 read test, detected as High Density, no READY signal, read each cylinder perfectly
DF0 write test, High Density, no READY signal, wrote 158 and 159 in 399ms (OK)

DF1 read test, detected as High Density, no READY signal, read each cylinder perfectly
DF1 write test, High Density, no READY signal, wrote 158 and 159 in 400ms (OK)

**Comment by tkurbad** [comment]
I'll try in the evening, when my two year old twins are asleep. :-) Thank you @keirf for implementing this so quickly!

**Comment by rjnorthrow** [comment]
Regarding the DS-DD and DS-HD, silly me, I've realised that this is correct when the HD floppy is in the drive before entering the menu

**Comment by tkurbad** [comment]
Btw., while implementing the READY signal for the HD drive (and getting it wrong at first) I realized that there must be yet another sequence aside from 0x00000000 and 0xAAAAAAAA that designates a SS-DD drive. Can you confirm that? (Not that it would be of any practical use nowadays, but perhaps testkit should deal with it nonetheless)

**Comment by tkurbad** [comment]
@rjnorthrow This confirms what @keirf said earlier: The HD drives emit the HD sequence only when a disk is inserted. Thus, I'll have to deal with the diskchange signal if I want to get it exactly as intended. I was hoping to be able to skip this part... ;-)

**Comment by tkurbad** [comment]
>  realized that there must be yet another sequence aside from 0x00000000 and 0xAAAAAAAA that designates a SS-DD drive.
Ah, @keirf already took care of it in his commit. Very nice!

**Comment by tkurbad** [comment]
@rjnorthrow Can you perchance tell me how long READY takes for your drives to get asserted after turning on the motor with a HD disk inserted?

**Comment by keirf** [comment]
@tkurbad Yes there are really only three useful IDs: DSDD, DSHD, and DSDD 48tpi (ie. 40 cylinders). There is no ID assignment or ID structure for specifying a single-sided drive. The Amiga never had a single-sided drive of course. The only reason an ID is assigned for 48tpi is because Commodore released the A1020.

**Comment by rjnorthrow** [comment]
@tkurbad If I'm reading this correctly, it can take over one second.

[https://photos.app.goo.gl/cwBPoccVEehnvv2JA]MTROn->RDY0

**Comment by tkurbad** [comment]
I see. Just read one of your earlier messages more thoroughly and want to comment on the motor-to-ready issue. My drive is usually READY within about 850 ms after motor on with HD disks. This doesn't seem to pose a problem for AmigaOS. With DD it gets READY in about half the time (as expected).
I don't know how the Chinons handle it, but I guess they might be quicker in HD mode as well.
In any case I want to avoid guessing and base the assertion of READY on the INDEX pulses for a busy drive as intended. Thus I'm very curious about how @rjnorthrow 's drives handle READY in the motor spinup case.

**Comment by tkurbad** [comment]
@rjnorthrow that makes sense to me. The motor's inertia contributes much more when spun up slowly, so this can take very well up to several INDEX cycles.

**Comment by rjnorthrow** [comment]
Could it be that the drives are now just 'old' and the motors are no longer quite as sprightly?

**Comment by tkurbad** [comment]
However, than it makes not much sense to assess late READY for HD disks at all.

**Comment by tkurbad** [comment]
Yes, mechanical wear and hardened grease certainly contribute to the motor running less smoothly.

**Comment by tkurbad** [comment]
@rjnorthrow do the INDEX pulses for your drives come at evenly spaced intervals after the assertion of READY?  My test Sony does very well in this regard, however I heard of drives that hold the low RPM very badly...

**Comment by rjnorthrow** [comment]
Will do. Am out at the moment

**Comment by keirf** [comment]
AmigaOS doesn't use Ready signal except for ID sequence detection. Hence why it works fine with modded PC drives that don't have a Ready signal at all (eg Escom A1200 Amigas).

**Comment by keirf** [comment]
I propose to increase the late deadline to 750ms (DD) and 1500ms (HD). I will time out on Ready detection after 1000ms and 2000ms respectively. Does that sound reasonable?

**Comment by rjnorthrow** [comment]
Just did another test, that time both drives were ready in <850ms with an HD floppy; best case was 575ms. With motor on, they both were exactly 200.1ms between INDEX pulses when settled down (after a second or so). The proposed deadlines seem reasonable to me @keirf

**Comment by keirf** [comment]
I may get rid of the arbitrary "late" deadline altogether. These old drives seem to regularly be slow to report ready, I'm not sure it's a useful or actionable warning. The absolute deadlines sound workable then, though I might tweak the DD absolute deadline up to 1250ms.

**Comment by tkurbad** [comment]
@keirf didn't AmigaOS versions prior to 3.0 need a proper READY signal? That leaves only 2.05 if you want to use HD drives, but my board should be universal, i.e. I want it to be able to generate a valid READY even for drives with shorted HD sensor that are hence permanently set to DD mode.

**Comment by keirf** [comment]
Okay here's the latest build. Most noticeable will be the changed reporting on the READY signal. Please see how it goes. For your real drives it should flatly report the time taken to assert READY after Motor On. All that "it's late" stuff is gone!

[atk_36_2.zip](https://github.com/keirf/Amiga-Stuff/files/5323679/atk_36_2.zip)

**Comment by keirf** [comment]
@tkurbad I don't believe any AmigaOS has ever checked READY. I just booted Workbench 1.3 on Kickstart 1.3 from a Gotek with pin 34 configured NC (never asserted).

**Comment by rjnorthrow** [comment]
Re: atk_36_2.zip, all good, READY asserted after (up to) 1.2 seconds on reads and writes, no late messages

**Comment by tkurbad** [comment]
@keirf good to know, than it's definitely for custom trackloaders only.

**Comment by tkurbad** [comment]
I'll try the new atk tomorrow. Just learned how the diskchange signal works. Shouldn't be hard to integrate buffering it in my little board and combining it with the DD switch.

**Comment by keirf** [comment]
All good. I think I'll kick out a release now.

**Comment by tkurbad** [comment]
@keirf just to add: Thanks again for the phenomenal support! My drive works much better now with DISKCHANGE being properly evaluated. Thanks to atk, I also found several bugs in my µC code regarding the id sequence and READY handling in general...

**Comment by keirf** [comment]
Pleased to hear it. The signal test sure is useful :)

**Comment by keirf** [comment]
@tkurbad Thanks for the donation!
