### ISSUE TITLE
Set RTC from SysTest

### ISSUE THREAD

**Issue by SukkoPera** [keirf/Amiga-Stuff#4]
I think the only major feature currently missing in SysTest is the ability to set the RTC to an arbitrary date.

It would be nice if it could be added :).

**Comment by SukkoPera** [comment]
Well, what I was thinking is just something along the lines of:
F1: Reset clock
F2: Hours +1
F3: Minutes +1
F4: Day +1
F5: Month +1
F6: Year +1

All values wrap around at their natural limits, except maybe for the year, for which a Year-1 key could be useful.

**Comment by keirf** [comment]
That's quite a good idea. Maybe for v1.2 then :)
