### ISSUE TITLE
ATK fails on 2MB Chip mem A500 Rev6 with Kick3.1.4

### ISSUE THREAD

**Issue by Alexco500** [keirf/Amiga-Stuff#41]
Hi,
I modified my A500 to have 2MB Chip mem, like it is done here:
http://www.rasterline.com/images/amiga/A500_REV6A_2MEG_CHIP.jpg

It works without issues, but ATK fails unpredictable during  memory test with Kick3.1.4 with an exception (black screen).
With Kick1.3, the test runs fine. Other mem test tools (like MBRTest-2) do not have issues, regardless of Kick version.

**Comment by keirf** [comment]
List all the Kickstart memory regions under Kick 1.3 and 3.1.4 (it is option F2 in the memory tests).

**Comment by Alexco500** [comment]
First is Kick 3.1.4 with exception

**Comment by Alexco500** [comment]
This one is with kick1.3

**Comment by keirf** [comment]
You need to log in and attach them on the github portal, or you need to provide links to an external host of the pictures. Attachments are removed from emails.

**Comment by Alexco500** [comment]
Sorry, didn’t know that. Updated my posts above.

**Comment by keirf** [comment]
Ok thanks. Very odd. The Kickstart memory list is identical in both cases (just the 2MB chip). Retrieving the memory list is the only thing ATK uses Kickstart for. Kickstart is unused/disabled when ATK runs.

The exception is not very helpful: It looks like the CPU has ended up executing at address 0. But it's not clear why.

I assume it is "Test All Memory" (F1) that you run, not "Direct Scan" (F3)?

Perhaps try testing a subset of the 2MB? You can test a memory region and edit the start/end memory addresses, using the Kickstart Memory List (F2) option.

For that matter, you could try the "Direct Scan" (F3), too.

**Comment by Alexco500** [comment]
I checked now different memory regions, small ones as well as half meg ones. Sooner or later it will crash with Kick3.1.4.
But everything else I throw onto the machine runs without issues, games, demos, memtests,..
Is the system disabled during mem test? I mean, I can move the mouse while waiting for the crash.

**Comment by keirf** [comment]
ATK runs the mouse itself. It chucks out the OS as it starts, after collecting the memory lists.

Is it actually related to the memory test at all? What if you leave it sitting at a menu for a while?

**Comment by Alexco500** [comment]
So, I guess we can close the issue here and call it a false positive. Since I need to change the Kickstart  for testing, I installed my old Kick switch. Since then the test runs without issues the whole day. I guess I have a broken solder joint or so, sorry for that.
