### ISSUE TITLE
Voltmace Analogue Joystick axis swapped and movement restricted to top left of box.

### ISSUE THREAD

**Issue by SpaceFlightOrange** [keirf/Amiga-Stuff#42]
Im seeing the axis on my Voltmace joystick swapped in the test so that left/right show as up/down and vice-versa, and restricted to the top left of the movement box. i know the joystick works fine in Microprose F1 etc. 

Would it be possible to add a calibration feature?

**Comment by keirf** [comment]
The whole point is to show you what range you really are getting, and on what axes (compared with the Amiga "standard").

If you can swap axes and calibrate in games then... fine. :) But it's not Amiga standard. Could be a PC stick for example (they use different pot values).

**Comment by SpaceFlightOrange** [comment]
It is an Amiga joystick, I'll investigate further.
