### ISSUE TITLE
Rom check glitch: custom roms 

### ISSUE THREAD

**Issue by roc-eab** [keirf/Amiga-Stuff#43]
Hello,

Grateful for having added the KS reading in the tool.

A small glitch. When using not standard roms (in one of my cases, a custom KS 1.3 with the scsi.device to boot on a A600) the ATK hangs on startup. I mean, it shows the red and blue screen without text.

Would it be possibile to bypass that check and just shows undetected or whatever you like in these corner cases?

Thank you and keep up the good work!

**Comment by keirf** [comment]
Can you confirm that earlier versions of ATK do work? Eg. does v1.14 work, but v1.15 does not?

**Comment by keirf** [comment]
Also are you able to supply me the offending ROM to test against? You can email me if you like.

**Comment by roc-eab** [comment]
Hello,

Problem solved. Most likely it was me stupid to burn a dummy one staight from China. I erased a working 27C400 and burned over it and the problem vanished. ATK 1.16 works well. Out of curiosity tried earlier version like 1.14 and works well too.

Apologies for that and thanks for the replied. I am sending anyhow the rom for your info thrugh email.

**Comment by keirf** [comment]
Thanks I had a look. Nothing there that would make ATK crash or hang of course. Perhaps the EPROM was actually bad?
