### ISSUE TITLE
My A1200 managed to crash the memory tester

### ISSUE THREAD

**Issue by xiphias256** [keirf/Amiga-Stuff#44]
I got an Amiga 1200 rev. 1D1, kickstart 3.0 with a 8MB fastram card from amigakit. Just after a few minutes of running ram test I get an Exception. 
![IMG_20210509_194343](https://user-images.githubusercontent.com/3736709/117584261-37462580-b10c-11eb-9d83-e38dfd000bb6.jpg)

**Comment by keirf** [comment]
CPU has crashed executing outside normal code area. Probably the memory test corrupted execution state. Hardware problem. Does it work without the 8mb card?

**Comment by xiphias256** [comment]
Yes, I have not had this issue without the expansion card yet. So faulty expansion card then?

**Comment by keirf** [comment]
Possibly. I don't know about compatibility with Kickstart 3.0. Do you have anything in the PCMCIA slot? Have you tried jumpering the RAM card for smaller amounts of RAM?
