### ISSUE TITLE
3.2 ROM Kickstart 47.96 not recognized

### ISSUE THREAD

**Issue by kinmami** [keirf/Amiga-Stuff#46]
the main splash screen reports ROM: unknown
it is a minor issue since all tests work normally

**Comment by keirf** [comment]
Please test this version:
[AmigaTestKit-5d15759.zip](https://github.com/keirf/Amiga-Stuff/files/6755087/AmigaTestKit-5d15759.zip)

**Comment by keirf** [comment]
Reported working and folded into new v1.17 release.
