### ISSUE TITLE
No docs about the toolchain needed

### ISSUE THREAD

**Issue by terriblefire** [keirf/Amiga-Stuff#5]
There are no docs about what toolchain is needed to build this stuff. Could we get some.. i just tried GCC 6 and vbcc ... neither work.

**Comment by keirf** [comment]
Stuff means specifically systest I imagine. I have not ported this to bebbo's amiga-gcc yet, instead it uses m68k-elf gcc toolchain to generate a binary blob which then gets Amiga hunk info slapped on by a script.

Specifically, try binutils 2.28 and gcc 7.1.0 configured for target `m68k-unknown-elf`.

**Comment by keirf** [comment]
Instructions added to the main README.
