### ISSUE TITLE
the adf fails to boot on a modified PC drive (real 3.5" disk).

### ISSUE THREAD

**Issue by arm1969** [keirf/Amiga-Stuff#52]
I have V1.16 that works without any issue on my modified Sony MPF 920 z/121 and z/131 drives. However, testing my A500 with V1.18 booting fails with a red screen! Initially I thought it's a disk problem but after using new disks, testing on another A500 and another modified drive  I can confirm the issue; it does not boot on a modified PC drive (Sony MPF920 to be specific).

**Comment by keirf** [comment]
Red immediately on loading bootblock with no further tracks loaded?

This is a trackdisk.device load error, or unable to allocate chip memory (unlikely!).

So... it's a disk or drive error.

**Comment by keirf** [comment]
Have you tried writing 1.16 onto a failing 1.18 disk and see if that works?

**Comment by arm1969** [comment]
As I have mentioned in my first comment, V1.16 loads on the same exact drive, same machine without ANY issues.
With V1.18 it gives the mentioned screen.

**Comment by keirf** [comment]
Okay, that's weird. I suggest to continue using V1.16. Perhaps read-test the V1.18 disk within V1.16, and perhaps memory test too.

There's no way that ATK can care it's loading on a modified PC drive. READY line behaviour can differ but this is ignored by the OS (which is used to load ATK; custom disk routines are not used except inside the floppy drive tests).
