### ISSUE TITLE
RTC chip reported incorrectly as M6242B

### ISSUE THREAD

**Issue by arm1969** [keirf/Amiga-Stuff#53]
I have a couple of memory expansions for the A500 with RTC based on the 72421 clock chip. The program reports incorrectly the M6242B chip. I suggest that the RTC chip number is removed unless there is a way to figure it out.

**Comment by keirf** [comment]
It is to distinguish from the incompatible RP5C01 used on A4000. 72421 is software compatible with MSM6242.

I can change it to "MSM6242 compatible RTC found at xxx"
