### ISSUE TITLE
ATK Head Calibration with analog alignment disk

### ISSUE THREAD

**Issue by mheyer32** [keirf/amiga-stuff#54]
To better support calibrating floppy drives with an analog head calibration disk and oscilloscope, the following features in the "Calibration tool" would be great:
1) Allow to choose which side to calibrate (i.e. upper or lower head). If both sides are being read, switch the head aligned with the Index signal, otherwise the oscilloscope output switches in the middle of the track which is hard to decipher
2) offer to seek to the current track from inside and/or outside ca 40 times ("step out")
3) In addition to track 0,40 and 80, offer track 2, 69, 75, 77 and 79  as preselection (see https://www.apple.asimov.net/documentation/hardware/storage/disks/Dysan%20Alignment%20Disk%20info.pdf for a list of tracks )
4) display rotation speed (in ms) and offer motor on/off in the Calibration tool as well (just like in the Signals test).

**Comment by dlitz** [comment]
Rudimentary control of the SIDE signal is added in pull request #61

**Comment by keirf** [comment]
Thanks for the PR. I will have a closer look when I have time but I'm pretty sure it all looks sensible.

**Comment by keirf** [comment]
(1) and (3) are now done.

For (2) it is always done in, then out, every time. Is that not good, and why do you need it done back to back 40 times?

For (4) I wonder why this needs to be duplicated from the signals test?

**Comment by mheyer32** [comment]
Very cool effort, thank you!

>> For (2) it is always done in, then out, every time. Is that not good, and why do you need it done back to back 40 times?

I got this number from some documentation explaining how to do disk calibration. That may not be exact science. I think it is to shake down any "looseness" in the head mechanism. When calibrating, one does need to manipulate the carriage mechanics. So moving the head a couple of times randomly and seeing if it can hit the calibration track either moving inwards or outwards shows if the stepping mechanism has any looseness. The current "re-seek" functionality is already good, but AFAIK seeks to the current track only from outside in(?).

* For (4) I wonder why this needs to be duplicated from the signals test?

This just makes it so that all calibration info is on one page and can be done from there. Showing the index signal as RPM and frequency is bonus. 
ATK could show the RPM and indicate via red/green color code if the RPM is within spec ( I believe 200ms +/- 5ms?)
Knowing if the RPM is inconsistent/jittery helps diagnosing issues with the spindle timing (often worn out capacitors).

The icing on the cake would be supporting HD drives as well when reading the track contents.

**Comment by keirf** [comment]
I think the requested enhancements are now all implemented. Re-seeking will now alternate between in-out-in and out-in-out.

**Comment by mheyer32** [comment]
Thank you very much!!
