### ISSUE TITLE
ATK : Help key crash the computer on hardware

### ISSUE THREAD

**Issue by Ja-mi** [keirf/amiga-stuff#55]
Hello,

Thanks for all the work done in this great piece of software. 

On real Amiga 500, with ACA500plus extension, pressing the _Help_ key always cause a crash instead of rebooting the computer. The crash screen is green and titled EXC1070330296 and showing register values. It seems to come from the internal exception handler of the ACA500plus. The 7-segment display of ACA show : E0

My configuration is :
Amiga 500 rev 6 
equiped with 512 kb trapdoor extension 
and ACA500plus !

I recorded a video to show you the problem : https://youtu.be/FR0Uk4Dvif4?t=39
You can rewind this video to see more details of my configuration.

I have also tried booting directly from the AmigaTestKit ADF, in plain kickstart 1.3, in ACA500 "cloaking" mode. Pressing Help also crash the machine with the same green screen.

**Comment by keirf** [comment]
I still need to test this on my ACA500plus! 

I don't really know why I agreed to implement a Reset Key, really, versus simply requiring use of C-A-A.

**Comment by Ja-mi** [comment]
Yes, it might be easier to remove that Help/Reset key implementation...
and tell the user to use the Ctrl+_A_+_A_ keys combination

**Comment by keirf** [comment]
That would be impossible in current design as ATK tramples memory. It would be quite a big change to make the layout system friendly.

I remember now the Reset key is for easy reset when no keyboard is attached. So it is needed.

It would be interesting to see whether ColdReboot via the ROM works for your setup with ACA500plus. Can you try a WB/CLI program which does a software reset? For example ColdReboot available on aminet?

**Comment by Ja-mi** [comment]
I have tried the tool CodlReboot by Miklós Árpád <alan elender hu> from Aminet. ColdReboot does reboot my system, without raising ACA500+ exception.

I ran it on my Amiga 500 from Workbench 3.2.1 (kickstart 3.2.1).

**Comment by Ja-mi** [comment]
I made an additional test, trying to disable maprom. So I set up an ACA500plus _cloaking profile_ that uses my mainboard Kickstart ROM, with "Map Rom" set to Off [(details here)](http://jamireste.free.fr/20220426_mapromoff.jpg)
I boot directly on AmigaTestKit v1.8 ADF then pressing the _Help_ key raises a similar E0 exception.

**Comment by keirf** [comment]
I see, and it is even the Mainboard ROM being used. Tsk. Well I will test it myself and I also emailed Jens the board designer.

**Comment by keirf** [comment]
Jens suggests it could be related to early bootmenu memory overlay, which can be disabled temporarily by putting the ACA500plus in de-brick mode. I think that is done by holding the DisMo button until the display blinks `0_`. And then try pressing the Reset key.

**Comment by Ja-mi** [comment]
I managed to switch my ACA500plus into de-brick mode (holding the card's DisMo button until `0_` blinks and then pressing Ctrl+_A_+_A_ on my Amiga).

When in de-brick mode, I booted to AmigaTestKit floppy then pressing _Help_ key reset **properly** my Amiga.

Just after that, I have pressed the DisMo button again to get out of de-brick mode, rebooted on the ATK floppy, pressed _Help_ key in ATK again and exception is raised again

I have repeated these tests several times to be sure.

**Comment by keirf** [comment]
Cheers. Something to do with that menu overlay then. I wonder if it can be worked around. Either that or I'll note it as an issue in next release.

**Comment by keirf** [comment]
At all times, if you C-A-A reset from ATK, I assume that always works?

**Comment by Ja-mi** [comment]
Yes, Ctrl+A+A always works as expected.

**Comment by keirf** [comment]
Could you give this version a try? You need to be logged in to Github for the dlownload to work:
https://github.com/keirf/amiga-stuff/suites/6264821157/artifacts/223572111

This replaces the reset routine with an alternative version from the Amiga's Hardware Reference Manual. It avoids jumping at the ACA's menu code and finds the actual Kickstart ROM entry point instead. It seems like it might work better here.

**Comment by Ja-mi** [comment]
OK

**Comment by Ja-mi** [comment]
I have juste tested several times with different ACA500plus profiles.

With this ATK build 1b68319, pressing the _Help_ key always reset properly my Amiga 500 (no exception is raised).

**Comment by keirf** [comment]
The fixed build on master branch, ready for next release: https://github.com/keirf/amiga-stuff/actions/runs/2226974005

**Comment by keirf** [comment]
Thanks for the release test!
