### ISSUE TITLE
Toggle the power LED brightness when a memory error is found

### ISSUE THREAD

**Issue by darrenfreeman** [keirf/amiga-stuff#56]
I had to memory test a machine which threw an error roughly twice a day. So I ran it with the monitor off, and occasionally checked on it.

I think it would be very helpful if the power LED toggled in brightness (i.e. toggle the audio filter status), to let the user know when to take a photo of the screen and then restart testing.

**Comment by keirf** [comment]
As in periodic blinking, say 1Hz cycle?

**Comment by darrenfreeman** [comment]
Something like that, although maybe not too similar to a guru meditation. But assuming the monitor is off, you will need to turn it on either way, to find out.

**Comment by keirf** [comment]
This is done and will be in the next release. Please reopen if you have any issues with this new feature.
