### ISSUE TITLE
Wrong Ram range for 4Mb ZIII cards

### ISSUE THREAD

**Issue by terriblefire** [keirf/Amiga-Stuff#6]
I’ve noticed that 4Mb Zorro iii (but not zorro ii) cards seem to show the range 

0x40000000-0x4040ffff

On systest. Should be 
0x40000000-0x403fffff

Causes systest to fail when testing the ram.

**Comment by keirf** [comment]
For Z3 space I will try rounding to nearest 1MB boundaries rather than rounding down/up to 64kB boundary (for lower/upper bounds resp.). Please test the attached version of systest, which implements this change:

[systest_6_1.zip](https://github.com/keirf/Amiga-Stuff/files/2529270/systest_6_1.zip)

**Comment by terriblefire** [comment]
I shall give it a whirl after work. Thanks for fixing quickly.

**Comment by terriblefire** [comment]
Fixed for the TF534.. many thanks
