### ISSUE TITLE
No 10kHz with my A1000

### ISSUE THREAD

**Issue by Gliou** [keirf/amiga-stuff#66]
Hi,
Is it possible (yes) to increase and decease ( + or - 500Hz )in sound menu ?

**Comment by Gliou** [comment]
No 10kHz with two Amiga 1000 (NTSC & PAL)

**Comment by keirf** [comment]
A1000 low-pass filter cannot be disabled in software so you will never hear 10kHz. This is also true for revision 3 A500.

**Comment by keirf** [comment]
I haven't thought about allowing configurable frequency. I could add some more frequency options to the F5 list if that's useful?
