### ISSUE TITLE
Kickstart 1.3 eprom uv AM27C400 Kickstart recognized

### ISSUE THREAD

**Issue by danko79** [keirf/amiga-stuff#68]
Hi, i have Amiga 500 REV5 put kickstart 1.3 on eprom uv AM27C400 and the ATK 1.20 Kickstart not recognized.
https://i.postimg.cc/3RDchbcz/kick.jpg

**Comment by keirf** [comment]
Maybe there's a data error in the header of the EPROM, or ROM address code is not working quite properly, as the 256kB ROM should be shadowed at F80000 (which is where ATK looks for it).

**Comment by danko79** [comment]
> Maybe there's a data error in the header of the EPROM, or ROM address code is not working quite properly, as the 256kB ROM should be shadowed at F80000 (which is where ATK looks for it).

So do you recommend me to try another UV eprom?

**Comment by keirf** [comment]
Or verify the one you have in your EPROM programmer (you can read as well as write them).

**Comment by danko79** [comment]
Solved, on the A500 REV5 need eprom adapter.

If you wish to upgrade your Amiga 500, Revision 5 by any newer kickstart you will need this adapter as Amiga 500, Revision 5 is not able to read any programmable kickstarts

**Comment by keirf** [comment]
Oh yes I forgot about that, you need stronger pullups I think. Good call, I'll remember that for next time!
