### ISSUE TITLE
Port 2 default option

### ISSUE THREAD

**Issue by LinuxJedi** [keirf/amiga-stuff#71]
Not sure if this is possible, but it would be nice to have a boot-time option to use port 2 as the mouse.

I've received some A1200s motherboards to repair in the past which do not come with the separate mouse board. There may also be machines with a dead port 1, but working port 2.

For now I've created a branch for anyone with this problem that uses port 2 as the mouse and switches port 1 and port 2 on the joy/mouse test: https://github.com/LinuxJedi/amiga-stuff/tree/ATK-PORT2

**Comment by VincentGR76** [comment]
Not a proper fix for the particular case and I'm sorry about it, But until is (if) added, there is a workaround. You can use Lemmings two player mode that supports mouse.

**Comment by keirf** [comment]
I have to be a bit careful with boot detections like is port 2 fire asserted, because I want to work non-confusingly with minority broken boards (eg which might have that line asserted erroneously). So let me have a think. Perhaps just providing a separate build/adf is best...

**Comment by keirf** [comment]
By the way, why do you swap ports in the "joymouse" tests?

**Comment by LinuxJedi** [comment]
> Not a proper fix for the particular case and I'm sorry about it, But until is (if) added, there is a workaround. You can use Lemmings two player mode that supports mouse.

Unfortunately it still requires a mouse in port 1 for the menu. Sure, I could use the keyboard. But I'm usually running initial tests on boards without the keyboard. There are also keyboards with bad membranes, etc...

> I have to be a bit careful with boot detections like is port 2 fire asserted, because I want to work non-confusingly with minorly broken boards (eg which might have that line asserted erroneously). So let me have a think. Perhaps just providing a separate build/adf is best...

Yea, I was thinking about potential CIA LMB / Paula RMB issues when I mentioned it. Best idea I could come up with is something like DiagROM where it pauses for several seconds for you to hit a button, detecting a stuck button at boot. Not ideal, and I'm not recommending ATK does this.

> By the way, why do you swap ports in the "joymouse" tests?

Port 2 is now the mouse, so I wanted this to be mouse by default in the test instead of joystick. I tried setting `ports[1].type = T_MOUSE` and appropriate values for the rest of the struct, the result was weird corruption. I only gave myself half an hour to figure out the build system and figure out the code to patch it for my own usage. Switching `joy0dat`/`joy1dat` and `!port` was a quick and easy hack for now to build a disk that suited my needs for today.

If you know what I missed when setting that struct, please let me know and I'll simplify what I did. Potentially making it a compile-time option.

**Comment by keirf** [comment]
I'll have a look at joy/mouse when I'm back at keyboard on Sunday. and at least this whole thing can be supported in my tree behind a compile option. So you don't have to carry it.

**Comment by LinuxJedi** [comment]
> I'll have a look at joy/mouse when I'm back at keyboard on Sunday. And at least this whole thing can be supported in my tree behind a compile option. So you don't have to carry it.

No problem, let me know if there is anything I can help with.

**Comment by LinuxJedi** [comment]
Oh! That was dumb of me, I misinterpreted `ports[1].start_x` as the starting position for the controller, not the starting position for drawing the controller's box. That is why it was acting very weird for me. When I don't mess with that, swapping `T_MOUSE` and `T_JOYSTICK` in the ports struct works great. Facepalm moment :)

I'll update my branch accordingly.

**Comment by keirf** [comment]
Great, thanks!

**Comment by keirf** [comment]
I'm inclined now to support a mouse in either port *at the same time*. So you can just plug'n'play in either port. A straightforwardly broken port with any direction or button stuck on or off should not stop a mouse in the other port from behaving sensibly. This would mean I wouldn't take your change to joymouse.c, but that's just gravy really and easy enough for you to carry for yourself.

**Comment by keirf** [comment]
This will be in the next release of ATK, sometime soon(ish). Please reopen if you have any issues of any sort with the committed patch (design or implementation).

**Comment by LinuxJedi** [comment]
Awesome, many thanks. This would have also helped with a few A4000s I've repaired too with damaged pulls on port 1. Looking at the code I think it will be perfect. I can test tomorrow.
