### ISSUE TITLE
Incorrect CPU detection on Apollo Vampire Accelerators

### ISSUE THREAD

**Issue by Tallguy298** [keirf/amiga-stuff#75]
AmigaTestKit 1.21 displays the CPU on the main page as 68060 Rev 1.
I have an Amiga 600 with MantiCore accelerator.
This is identified as a 68080 with 68882 FPU.
Relevant info...
[CPU attention flags](http://adevnoo.wikidot.com/detect-080-code)
[SAGA chipset](http://www.apollo-core.com/index.htm?page=coding&tl=2)
[Vampire specific version](http://www.apollo-core.com/sagadoc/vampversion.htm) - $DFF3FC - 8bit Card Version / 8bit clock multiplier

Could this be incorporated into your next update?

Thankyou,
Alexander.

**Comment by keirf** [comment]
Accurate detection of modern soft cores is out of scope. Especially as current detection routine doesn't use Kickstart flags at all, and there's no docs on 080 CPU detection except via Kickstart flags. 

There probably is some detection method that hits the hardware directly but I don't have any Vampires to test it out and the published documentation is pants: I don't really trust that the question of what *is* a 68080 isn't a moving target. And there's little community support around this sort of thing (eg there's no WinUAE emulation of Vampire for software testing).
