### ISSUE TITLE
Disk seeking on A1020 (5.25" inch drive) broken

### ISSUE THREAD

**Issue by mheyer32** [keirf/amiga-stuff#76]
I have recently purchased a A1020 for fun and tried to run it through its courses in ATK. 
ATK detects the device type (device Id, number of tracks) perfectly, but fails seeking.

I.e. it cannot seek back to track 0 and thus cannot perform some of the tests.

I believe this might be due to ATK using the incorrect wait time between steps when issuing multiple step commands. They need to be longer than for 3.5" drives. I did not look up how long, but could find out if necessary.

**Comment by keirf** [comment]
Please can you try the fixed build linked below (you will need to be logged in to GitHub to see the Artifact download link):
https://github.com/keirf/amiga-stuff/actions/runs/12295522475

**Comment by mheyer32** [comment]
This definitely helped!
I can run the read test now and the calibration tests also move the head correctly.
One thing is a bit weird, though: while this version _does_ seek to track 0 in the Signal Test, it seems to try slam the head past its limits - is this intended?

**Comment by keirf** [comment]
There is a pointless max-cylinders probe at the start of the signal test. It doesn't belong in the signals test, and it's not very good or useful. So I'm removing it. I will have a new build for you shortly.

**Comment by keirf** [comment]
Here is a fixed build for you to try:
https://github.com/keirf/amiga-stuff/actions/runs/12328565141

**Comment by mheyer32** [comment]
Thank you! The head banging stopped now. I can perform signal test, calibration test and read test either the A1020.
![image](https://github.com/user-attachments/assets/6893cf47-b28b-47cd-8078-6286113abea1)![image](https://github.com/user-attachments/assets/cee07957-9b23-472f-b030-867406a5f53c)

The write test, though, doesn't seem to respect the 40 track limit:
![image](https://github.com/user-attachments/assets/5cd4da8c-601c-4c05-bb29-bb444f92c410)

**Comment by keirf** [comment]
The write test is correct, but the final message is wrong. And it would be clearer as cyl.head perhaps rather than a track number. I will fix that and make another build.

**Comment by keirf** [comment]
Here's another build for you to try. It fixes the track-number reporting in the write test, so that's the only thing you need to try. Let me know how it goes: https://github.com/keirf/amiga-stuff/actions/runs/12372782259

**Comment by mheyer32** [comment]
Works like a charm!
