### ISSUE TITLE
Hang on A500 with aca500plus

### ISSUE THREAD

**Issue by blark** [keirf/Amiga-Stuff#8]
Just wondering if this is a known issue or not. I've got an ACA500plus and SysTest seems to hang almost as soon as I launch it. It accepts input sometimes for about a second and then stops, the mouse still moves but no other input is recognized. 

I should also mention that I put an 8372A Fat Agnus into it (an old v1 motherboard) so i could use 1MB chip ram. I've tried with the chip ram on and off with no luck. I've also played with the Aca500plus settings, disabling various things to try and get it to work to no avail. 

Thanks

**Comment by keirf** [comment]
V1 mobo? What revision is that?

No other reports of this but I do have a aca500plus so could try this myself. I also have a 1mb chip mod on my test 500 board.

**Comment by blark** [comment]
Sorry it is a rev 5 motherboard. Thanks a lot for the quick response and trying this out. I'm curious if there is something more wrong with this system or if it's just the ACA500plus that's causing the issue.

**Comment by keirf** [comment]
Can you put a fatter agnus in rev 5 then? I can never remember the exact incompatibilities between agnus plcc versions...

**Comment by blark** [comment]
I think that might be my problem, you can use 8372A but you have to do a few other things like cut a trace and solder another. And then something with Gary -- I forgot about that. Going to do some more research and I'll post back here. 

If you do try it with the ACA500plus please let me know how it goes! Thanks!

**Comment by keirf** [comment]
Can you try the original agnus?

**Comment by blark** [comment]
Had to fly out of town, I will check when I get home and update just in case anyone else has the same issue.

**Comment by keirf** [comment]
SysTest working fine with my ACA500plus.
