### ISSUE TITLE
No .adf file in testkit folder

### ISSUE THREAD

**Issue by Garezec** [keirf/Amiga-Stuff#9]
Hi,

There doesn't seem to be a .adf file in the testkit folder as described in the readme.

Regards

Chris

**Comment by keirf** [comment]
Yes it's right there, AmigaTestKit.adf, inside the AmigaTestKit-v1.3/ root folder.

**Comment by Garezec** [comment]
Sorry my bad. When I unzipped the download i was just looking in the Amiga Stuff Master folder. Found it cheers - awesome applications, great work btw.

**Comment by keirf** [comment]
Ah you built from source? Fair enough, there's some other nice stuff in there too. I'm quite pleased with the exe packer too 😊
